version: '3.2'
services:
    nest-recipes:
      build:
        context: .
        dockerfile: 'Dockerfile'
      ports:
        - '3000:3000'
      environment:
        DB_HOST: recipesdb
        DB_USER: postgres
        DB_PASS: postgres
    recipesdb:
      image: postgres:latest
      restart: always
      container_name: recipesdb
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=recipes
      volumes:
        - ./docker_postgres_init.sh:/docker-entrypoint-initdb.d/docker_postgres_init.sh
        - ./data:/var/lib/postgresql/data:z